### PR TITLE
Updated Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by kugiigi** [comment]
That was fast :)
I'm not an expert with translations but it seems like you'll have to update the template first as I see untranslated texts.
I honestly don't know how but they appeared in the file after I compiled and ran the app.
This version is a complete rewrite/redesigned so there are many new words.

**Comment by Vistaus** [comment]
That's odd, I didn't see any new strings in the template. How do I update the template?

**Comment by kugiigi** [comment]
I'm so sorry I forgot to mention. I changed the main branch to `main`.
And it is now only for focal. No xenial release for now.

**Comment by Vistaus** [comment]
Sorry for my late reply. I checked out the main branch, but I still don't see any new strings.

**Comment by kugiigi** [comment]
Are you sure you checked it out correctly? I manually checked and I saw the new strings in the template and the `po` files. How do you checkout?
Maybe you try this
`git clone <repo url> --single-branch --branch main`

**Comment by Vistaus** [comment]
Thanks. That didn't work either, so I just deleted and reforked the repo and now I do see the new strings. Will open a new PR once I'm done updating. :)

**Comment by kugiigi** [comment]
Okay, sorry about this. I guess I shouldn't have changed the main branch. There was a warning about the consequences and I ignored them 😅

**Comment by Vistaus** [comment]
No worries, we both figured it out and it's all good now. 🙂

**Pull request closed without merging**
